---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/sigil -v
      register: sigil_test_output
    - name: sigil -v
      debug:
        msg: '{{ sigil_test_output.stdout }}'
