---
- name: Testing andrewrothstein.sigil
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'sigil -v'
      ansible.builtin.command: sigil -v
      changed_when: false
      register: sigil_test_output
    - name: Output from 'sigil -v'
      ansible.builtin.debug:
        msg: '{{ sigil_test_output.stdout }}'
