---
- name: download tgz
  become: yes
  become_user: root
  get_url:
    url: '{{sigil_tgz_url}}'
    dest: /tmp/{{sigil_tgz}}
    mode: 0644

- name: mkdir versioned dir
  become: yes
  become_user: root
  file:
    path: '{{sigil_target_dir}}'
    state: directory
    mode: 0755

- name: unarchive...
  become: yes
  become_user: root
  unarchive:
    copy: no
    src: /tmp/{{sigil_tgz}}
    dest: '{{sigil_target_dir}}'

- name: link...
  become: yes
  become_user: root
  file:
    src: '{{sigil_target_dir}}/sigil'
    dest: '{{sigil_install_dir}}/sigil'
    state: link
