---
- name: Downloading {{ sigil_url }} to {{ sigil_exe }}
  become: true
  become_user: root
  ansible.builtin.get_url:
    url: '{{ sigil_url }}'
    dest: '{{ sigil_exe }}'
    mode: '755'

- name: Linking {{ sigil_link }} to {{ sigil_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ sigil_exe }}'
    dest: '{{ sigil_link }}'
    state: link
